# Cleaning the synthesized data

In [2]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [8]:
Accused = pd.read_csv("../synthetic_data/Accused.csv")
ActSectionAssociation = pd.read_csv("../synthetic_data/ActSectionAssociation.csv")
ArrestSurrender = pd.read_csv("../synthetic_data/ArrestSurrender.csv")
CaseMaster = pd.read_csv("../synthetic_data/CaseMaster.csv")
Chargesheet = pd.read_csv("../synthetic_data/ChargesheetDetails.csv")
ComplaintDetails = pd.read_csv("../synthetic_data/ComplainantDetails.csv")
Court = pd.read_csv("../synthetic_data/Court.csv")
Employee = pd.read_csv("../synthetic_data/Employee.csv")
Unit = pd.read_csv("../synthetic_data/Unit.csv")

Exploring some of the Synthetic Data using pandas to ensure invalid data is not pushed into the database
Rest have been manually checked

Starting with Accused.csv

In [25]:
Accused.head()

   AccusedMasterID  CaseMasterID      AccusedName  AgeYear  GenderID PersonID
0                1             1     Ganesh Achar       38         1       A1
1                2             1        Nasir Rai       35         1       A2
2                3             1  Basavaraj Desai       37         1       A3
3                4             1          Nagaraj       38         1       A4
4                5             3     Prasad Desai       63         1       A1

In [26]:
Accused.shape

(22909, 6)

In [27]:
Accused.info()

<class 'pandas.DataFrame'>
RangeIndex: 22909 entries, 0 to 22908
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   AccusedMasterID  22909 non-null  int64
 1   CaseMasterID     22909 non-null  int64
 2   AccusedName      22909 non-null  str
 3   AgeYear          22909 non-null  int64
 4   GenderID         22909 non-null  int64
 5   PersonID         22909 non-null  str
dtypes: int64(4), str(2)
memory usage: 1.0 MB

In [28]:
Accused.isnull().sum()

AccusedMasterID    0
CaseMasterID       0
AccusedName        0
AgeYear            0
GenderID           0
PersonID           0
dtype: int64

In [29]:
## Checking duplicates in CaseMasterID in Accused.csv
Accused['CaseMasterID'].duplicated().sum()

np.int64(9717)

The major reason for duplicates in CaseMasterID is that there are multiple accused in Accused table data



For now, no such issues found in Accused

Getting started with ActSectionAssociation.csv

In [30]:
ActSectionAssociation.head()

   CaseMasterID  ActID  SectionID  ActOrderID  SectionOrderID
0             1    BNS    BNS-351           1               1
1             2  KPACT  KPACT-110           1               1
2             3  KPACT  KPACT-110           1               1
3             3    IPC    IPC-504           2               2
4             4    BNS    BNS-318           1               1

In [31]:
ActSectionAssociation.info()

<class 'pandas.DataFrame'>
RangeIndex: 24085 entries, 0 to 24084
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CaseMasterID    24085 non-null  int64
 1   ActID           24085 non-null  str
 2   SectionID       24085 non-null  str
 3   ActOrderID      24085 non-null  int64
 4   SectionOrderID  24085 non-null  int64
dtypes: int64(3), str(2)
memory usage: 940.9 KB

In [32]:
ActSectionAssociation.isnull().sum()

CaseMasterID      0
ActID             0
SectionID         0
ActOrderID        0
SectionOrderID    0
dtype: int64

In [41]:
ActSectionAssociation['CaseMasterID'].duplicated().sum()

np.int64(9085)

The reason for multiple CaseMasterID to be duplicate can be the implication of multiple Acts (IPC, KPACT, etc) in a particular case

Conclusion: No issues with ActSectionAssociation.csv

Checking on ArrestSurrender.csv
---

In [34]:
ArrestSurrender.head()

,ArrestSurrenderID,CaseMasterID,ArrestSurrenderTypeID,ArrestSurrenderDate,ArrestSurrenderStateId,ArrestSurrenderDistrictId,PoliceStationID,IOID,CourtID,AccusedMasterID,IsAccused,IsComplainantAccused
0,1,1,1,2025-11-29,16,5,83,788,19,1,0,0
1,2,1,1,2025-11-25,16,5,83,789,19,2,1,0
2,3,1,1,2025-11-27,16,5,83,787,19,3,1,0
3,4,1,1,2025-11-24,16,5,83,787,19,4,1,0
4,5,3,1,2023-11-05,16,6,158,1363,25,7,1,0

In [35]:
ArrestSurrender.info()

<class 'pandas.DataFrame'>
RangeIndex: 16529 entries, 0 to 16528
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ArrestSurrenderID          16529 non-null  int64
 1   CaseMasterID               16529 non-null  int64
 2   ArrestSurrenderTypeID      16529 non-null  int64
 3   ArrestSurrenderDate        16529 non-null  str
 4   ArrestSurrenderStateId     16529 non-null  int64
 5   ArrestSurrenderDistrictId  16529 non-null  int64
 6   PoliceStationID            16529 non-null  int64
 7   IOID                       16529 non-null  int64
 8   CourtID                    16529 non-null  int64
 9   AccusedMasterID            16529 non-null  int64
 10  IsAccused                  16529 non-null  int64
 11  IsComplainantAccused       16529 non-null  int64
dtypes: int64(11), str(1)
memory usage: 1.5 MB

In [36]:
### Convert ArrestSurrender['ArrestSurrenderDate'] to datetime format
ArrestSurrender['ArrestSurrenderDate'] = pd.to_datetime(ArrestSurrender['ArrestSurrenderDate'], errors='coerce')
ArrestSurrender.info()

<class 'pandas.DataFrame'>
RangeIndex: 16529 entries, 0 to 16528
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ArrestSurrenderID          16529 non-null  int64
 1   CaseMasterID               16529 non-null  int64
 2   ArrestSurrenderTypeID      16529 non-null  int64
 3   ArrestSurrenderDate        16529 non-null  datetime64[us]
 4   ArrestSurrenderStateId     16529 non-null  int64
 5   ArrestSurrenderDistrictId  16529 non-null  int64
 6   PoliceStationID            16529 non-null  int64
 7   IOID                       16529 non-null  int64
 8   CourtID                    16529 non-null  int64
 9   AccusedMasterID            16529 non-null  int64
 10  IsAccused                  16529 non-null  int64
 11  IsComplainantAccused       16529 non-null  int64
dtypes: datetime64[us](1), int64(11)
memory usage: 1.5 MB

In [37]:
ArrestSurrender.isnull().sum()

ArrestSurrenderID            0
CaseMasterID                 0
ArrestSurrenderTypeID        0
ArrestSurrenderDate          0
ArrestSurrenderStateId       0
ArrestSurrenderDistrictId    0
PoliceStationID              0
IOID                         0
CourtID                      0
AccusedMasterID              0
IsAccused                    0
IsComplainantAccused         0
dtype: int64

In [38]:
ArrestSurrender.duplicated().sum()

np.int64(0)

In [45]:
ArrestSurrender['CaseMasterID'].duplicated().sum()

np.int64(5956)

One major reason for this can be that different Accused surrendered in different timelines

Getting started with CaseMaster.csv
---

In [46]:
CaseMaster.head()

,CaseMasterID,CrimeNo,CaseNo,CrimeRegisteredDate,PolicePersonID,PoliceStationID,CaseCategoryID,GravityOffenceID,CrimeMajorHeadID,CrimeMinorHeadID,CaseStatusID,CourtID,IncidentFromDate,IncidentToDate,InfoReceivedPSDate,latitude,longitude,BriefFacts
0,1,100050083202500001,202500001,2025-11-20,788,83,1,2,6,30,8,19,2025-11-20 10:07:25,2025-11-20 10:07:25,2025-11-20 11:54:49,13.115182,77.524311,Information was received regarding rioting dur...
1,2,100220093202500001,202500001,2025-12-17,864,93,1,2,12,61,2,84,2025-12-16 16:21:47,2025-12-16 16:22:47,2025-12-17 18:30:46,12.415984,76.690888,Information was received regarding arms act vi...
2,3,600060158202300001,202300001,2023-10-28,1368,158,6,3,6,30,4,27,2023-10-28 17:15:04,2023-10-28 17:18:04,2023-10-28 20:26:36,17.681781,77.343568,Information was received regarding rioting lat...
3,4,200030105202500001,202500001,2025-02-23,969,105,2,2,5,27,6,11,2025-02-22 07:40:32,2025-02-22 08:24:32,2025-02-23 12:41:30,15.939614,74.672017,The complainant reported an act of elder abuse...
4,5,100110095202200001,202200001,2022-11-15,884,95,1,3,2,8,8,40,2022-11-15 08:19:30,2022-11-15 08:25:30,2022-11-15 21:39:29,12.976804,74.632775,"A case of theft came to notice late at night, ..."

In [47]:
CaseMaster.info()

<class 'pandas.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   CaseMasterID         15000 non-null  int64
 1   CrimeNo              15000 non-null  int64
 2   CaseNo               15000 non-null  int64
 3   CrimeRegisteredDate  15000 non-null  str
 4   PolicePersonID       15000 non-null  int64
 5   PoliceStationID      15000 non-null  int64
 6   CaseCategoryID       15000 non-null  int64
 7   GravityOffenceID     15000 non-null  int64
 8   CrimeMajorHeadID     15000 non-null  int64
 9   CrimeMinorHeadID     15000 non-null  int64
 10  CaseStatusID         15000 non-null  int64
 11  CourtID              15000 non-null  int64
 12  IncidentFromDate     15000 non-null  str
 13  IncidentToDate       15000 non-null  str
 14  InfoReceivedPSDate   15000 non-null  str
 15  latitude             15000 non-null  float64
 16  longitude            15000 non-null  float64
 17  BriefFacts           15000 non-null  str
dtypes: float64(2), int64(11), str(5)
memory usage: 2.1 MB

In [48]:
## Converting CrimeRegisteredDate to datetime format
CaseMaster['CrimeRegisteredDate'] = pd.to_datetime(CaseMaster['CrimeRegisteredDate'], errors='coerce')

In [50]:
## Converting IncidentFromDate, IncidentToDate,InfoReceivedPSDate to datetime format
CaseMaster['IncidentFromDate'] = pd.to_datetime(CaseMaster['IncidentFromDate'], errors='coerce')
CaseMaster['IncidentToDate'] = pd.to_datetime(CaseMaster['IncidentToDate'], errors='coerce')
CaseMaster['InfoReceivedPSDate'] = pd.to_datetime(CaseMaster['InfoReceivedPSDate'], errors='coerce')

In [51]:
CaseMaster.info()

<class 'pandas.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   CaseMasterID         15000 non-null  int64
 1   CrimeNo              15000 non-null  int64
 2   CaseNo               15000 non-null  int64
 3   CrimeRegisteredDate  15000 non-null  datetime64[us]
 4   PolicePersonID       15000 non-null  int64
 5   PoliceStationID      15000 non-null  int64
 6   CaseCategoryID       15000 non-null  int64
 7   GravityOffenceID     15000 non-null  int64
 8   CrimeMajorHeadID     15000 non-null  int64
 9   CrimeMinorHeadID     15000 non-null  int64
 10  CaseStatusID         15000 non-null  int64
 11  CourtID              15000 non-null  int64
 12  IncidentFromDate     15000 non-null  datetime64[us]
 13  IncidentToDate       15000 non-null  datetime64[us]
 14  InfoReceivedPSDate   15000 non-null  datetime64[us]
 15  latitude             15000 non-null  float64
 16  longitude            15000 non-null  float64
 17  BriefFacts           15000 non-null  str
dtypes: datetime64[us](4), float64(2), int64(11), str(1)
memory usage: 2.1 MB

In [60]:
## Checking if the IncidentFromDate is before the IncidentToDate in CaseMaster dataframe
for index, row in CaseMaster.iterrows():
    incident_from_date = row['IncidentFromDate']
    incident_to_date = row['IncidentToDate']
    
    if pd.notnull(incident_from_date) and pd.notnull(incident_to_date) and incident_from_date > incident_to_date:
        print(f"Warning: IncidentFromDate {incident_from_date} is after IncidentToDate {incident_to_date} for CaseMasterID {row['CaseMasterID']}")

In [63]:
## Checking if the CrimeRegisteredDate is after one day the IncidentFromDate and IncidentToDate
for index, row in CaseMaster.iterrows():
    crime_date = row['CrimeRegisteredDate']
    incident_from_date = row['IncidentFromDate']
    incident_to_date = row['IncidentToDate']
    one_day_after_incident_from = incident_from_date + pd.Timedelta(days=1)
    one_day_after_incident_to = incident_to_date + pd.Timedelta(days=1)

    if pd.notnull(crime_date) and pd.notnull(incident_from_date) and crime_date < one_day_after_incident_from:
        print(f"Warning: CrimeRegisteredDate {crime_date} is before one day after IncidentFromDate {one_day_after_incident_from} for CaseMasterID {row['CaseMasterID']}")

    if pd.notnull(crime_date) and pd.notnull(incident_to_date) and crime_date < one_day_after_incident_to:
        print(f"Warning: CrimeRegisteredDate {crime_date} is before one day after IncidentToDate {one_day_after_incident_to} for CaseMasterID {row['CaseMasterID']}")

Warning: CrimeRegisteredDate 2025-11-20 00:00:00 is before one day after IncidentFromDate 2025-11-21 10:07:25 for CaseMasterID 1
Warning: CrimeRegisteredDate 2025-11-20 00:00:00 is before one day after IncidentToDate 2025-11-21 10:07:25 for CaseMasterID 1
Warning: CrimeRegisteredDate 2025-12-17 00:00:00 is before one day after IncidentFromDate 2025-12-17 16:21:47 for CaseMasterID 2
Warning: CrimeRegisteredDate 2025-12-17 00:00:00 is before one day after IncidentToDate 2025-12-17 16:22:47 for CaseMasterID 2
Warning: CrimeRegisteredDate 2023-10-28 00:00:00 is before one day after IncidentFromDate 2023-10-29 17:15:04 for CaseMasterID 3
Warning: CrimeRegisteredDate 2023-10-28 00:00:00 is before one day after IncidentToDate 2023-10-29 17:18:04 for CaseMasterID 3
Warning: CrimeRegisteredDate 2025-02-23 00:00:00 is before one day after IncidentFromDate 2025-02-23 07:40:32 for CaseMasterID 4
Warning: CrimeRegisteredDate 2025-02-23 00:00:00 is before one day after IncidentToDate 2025-02-23 08:24:32 for CaseMasterID 4
Warning: CrimeRegisteredDate 2022-11-15 00:00:00 is before one day after IncidentFromDate 2022-11-16 08:19:30 for CaseMasterID 5
Warning: CrimeRegisteredDate 2022-11-15 00:00:00 is before one day after IncidentToDate 2022-11-16 08:25:30 for CaseMasterID 5
Warning: CrimeRegisteredDate 2025-07-03 00:00:00 is before one day after IncidentFromDate 2025-07-04 19:37:32 for CaseMasterID 6
Warning: CrimeRegisteredDate 2025-07-03 00:00:00 is before one day after IncidentToDate 2025-07-04 19:37:32 for CaseMasterID 6
Warning: CrimeRegisteredDate 2024-10-31 00:00:00 is before one day after IncidentFromDate 2024-10-31 00:55:44 for CaseMasterID 7
Warning: CrimeRegisteredDate 2024-10-31 00:00:00 is before one day after IncidentToDate 2024-10-31 01:39:44 for CaseMasterID 7
Warning: CrimeRegisteredDate 2025-11-05 00:00:00 is before one day after IncidentFromDate 2025-11-05 18:58:08 for CaseMasterID 10
Warning: CrimeRegisteredDate 2025-11-05 00:00:00 is before one day after IncidentToDate 2025-11-05 19:03:08 for CaseMasterID 10
Warning: CrimeRegisteredDate 2023-09-26 00:00:00 is before one day after IncidentFromDate 2023-09-26 13:51:59 for CaseMasterID 12
Warning: CrimeRegisteredDate 2023-09-26 00:00:00 is before one day after IncidentToDate 2023-09-26 14:27:59 for CaseMasterID 12
Warning: CrimeRegisteredDate 2025-10-24 00:00:00 is before one day after IncidentFromDate 2025-10-24 21:56:51 for CaseMasterID 13
Warning: CrimeRegisteredDate 2025-10-24 00:00:00 is before one day after IncidentToDate 2025-10-24 22:12:51 for CaseMasterID 13
Warning: CrimeRegisteredDate 2022-05-04 00:00:00 is before one day after IncidentFromDate 2022-05-04 14:10:00 for CaseMasterID 14
Warning: CrimeRegisteredDate 2022-05-04 00:00:00 is before one day after IncidentToDate 2022-05-04 14:49:00 for CaseMasterID 14
Warning: CrimeRegisteredDate 2025-09-28 00:00:00 is before one day after IncidentFromDate 2025-09-29 03:13:27 for CaseMasterID 15
Warning: CrimeRegisteredDate 2025-09-28 00:00:00 is before one day after IncidentToDate 2025-09-29 03:34:27 for CaseMasterID 15
Warning: CrimeRegisteredDate 2023-07-26 00:00:00 is before one day after IncidentFromDate 2023-07-26 07:05:41 for CaseMasterID 19
Warning: CrimeRegisteredDate 2023-07-26 00:00:00 is before one day after IncidentToDate 2023-07-26 07:07:41 for CaseMasterID 19
Warning: CrimeRegisteredDate 2024-11-23 00:00:00 is before one day after IncidentFromDate 2024-11-24 13:17:25 for CaseMasterID 20
Warning: CrimeRegisteredDate 2024-11-23 00:00:00 is before one day after IncidentToDate 2024-11-25 17:55:28 for CaseMasterID 20
Warning: CrimeRegisteredDate 2024-11-21 00:00:00 is before one day after IncidentFromDate 2024-11-21 02:16:30 for CaseMasterID 22
Warning: CrimeRegisteredDate 2024-11-21 00:00:00 is before one day after IncidentToDate 2024-11-21 02:40:30 for CaseMasterID 22
Warning: CrimeRegisteredDate 2025-09-15 00:00:00 is before one day after IncidentFromDate 2025-09-16 07:31:03 for CaseMasterID 23
Warning: CrimeRegisteredDate 2025-09-15 00:00:00 is before one day after IncidentToDate 2025-09-16 07:51:03 for CaseMasterID 23
Warning: CrimeRegisteredDate 2023-11-30 00:00:00 is before one day after IncidentFromDate 2023-11-30 00:28:50 for CaseMasterID 24
Warning: CrimeRegisteredDate 2023-11-30 00:00:00 is before one day after IncidentToDate 2023-11-30 00:49:50 for CaseMasterID 24
Warning: CrimeRegisteredDate 2021-03-15 00:00:00 is before one day after IncidentFromDate 2021-03-16 08:48:52 for CaseMasterID 27
Warning: CrimeRegisteredDate 2021-03-15 00:00:00 is before one day after IncidentToDate 2021-03-16 09:02:52 for CaseMasterID 27
Warning: CrimeRegisteredDate 2025-08-04 00:00:00 is before one day after IncidentFromDate 2025-08-04 09:02:06 for CaseMasterID 28
Warning: CrimeRegisteredDate 2025-08-04 00:00:00 is before one day after IncidentToDate 2025-08-04 09:32:06 for CaseMasterID 28
Warning: CrimeRegisteredDate 2024-05-27 00:00:00 is before one day after IncidentFromDate 2024-05-27 03:21:49 for CaseMasterID 29
Warning: CrimeRegisteredDate 2024-05-27 00:00:00 is before one day after IncidentToDate 2024-05-27 04:02:49 for CaseMasterID 29
Warning: CrimeRegisteredDate 2024-07-17 00:00:00 is before one day after IncidentFromDate 2024-07-17 12:59:15 for CaseMasterID 31
Warning: CrimeRegisteredDate 2024-07-17 00:00:00 is before one day after IncidentToDate 2024-07-17 13:08:15 for CaseMasterID 31
Warning: CrimeRegisteredDate 2024-10-28 00:00:00 is before one day after IncidentFromDate 2024-10-28 23:40:06 for CaseMasterID 32
Warning: CrimeRegisteredDate 2024-10-28 00:00:00 is before one day after IncidentToDate 2024-10-28 23:49:06 for CaseMasterID 32
Warning: CrimeRegisteredDate 2023-10-05 00:00:00 is before one day after IncidentFromDate 2023-10-06 00:09:06 for CaseMasterID 33
Warning: CrimeRegisteredDate 2023-10-05 00:00:00 is before one day after IncidentToDate 2023-10-06 00:41:06 for CaseMasterID 33
Warning: CrimeRegisteredDate 2023-09-23 00:00:00 is before one day after IncidentFromDate 2023-09-23 15:00:28 for CaseMasterID 35
Warning: CrimeRegisteredDate 2023-09-23 00:00:00 is before one day after IncidentToDate 2023-09-25 20:29:11 for CaseMasterID 35
Warning: CrimeRegisteredDate 2024-01-30 00:00:00 is before one day after IncidentFromDate 2024-01-31 17:15:00 for CaseMasterID 37
Warning: CrimeRegisteredDate 2024-01-30 00:00:00 is before one day after IncidentToDate 2024-02-01 00:46:19 for CaseMasterID 37
Warning: CrimeRegisteredDate 2024-10-28 00:00:00 is before one day after IncidentFromDate 2024-10-28 15:33:02 for CaseMasterID 38
Warning: CrimeRegisteredDate 2024-10-28 00:00:00 is before one day after IncidentToDate 2024-10-28 16:05:02 for CaseMasterID 38
Warning: CrimeRegisteredDate 2025-08-18 00:00:00 is before one day after IncidentFromDate 2025-08-19 10:23:53 for CaseMasterID 40
Warning: CrimeRegisteredDate 2025-08-18 00:00:00 is before one day after IncidentToDate 2025-08-19 10:33:53 for CaseMasterID 40
Warning: CrimeRegisteredDate 2024-07-22 00:00:00 is before one day after IncidentFromDate 2024-07-23 16:25:55 for CaseMasterID 46
Warning: CrimeRegisteredDate 2024-07-22 00:00:00 is before one day after IncidentToDate 2024-07-23 17:05:55 for CaseMasterID 46
Warning: CrimeRegisteredDate 2022-09-11 00:00:00 is before one day after IncidentFromDate 2022-09-11 08:31:35 for CaseMasterID 48
Warning: CrimeRegisteredDate 2022-09-11 00:00:00 is before one day after IncidentToDate 2022-09-11 08:55:35 for CaseMasterID 48
Warning: CrimeRegisteredDate 2025-10-10 00:00:00 is before one day after IncidentFromDate 2025-10-10 00:30:30 for CaseMasterID 49
Warning: CrimeRegisteredDate 2025-10-10 00:00:00 is before one day after IncidentToDate 2025-10-10 00:56:30 for CaseMasterID 49
Warning: CrimeRegisteredDate 2024-11-12 00:00:00 is before one day after IncidentFromDate 2024-11-12 21:18:42 for CaseMasterID 50
Warning: CrimeRegisteredDate 2024-11-12 00:00:00 is before one day after IncidentToDate 2024-11-12 21:19:42 for CaseMasterID 50
Warning: CrimeRegisteredDate 2024-06-18 00:00:00 is before one day after IncidentFromDate 2024-06-18 22:12:48 for CaseMasterID 51
Warning: CrimeRegisteredDate 2024-06-18 00:00:00 is before one day after IncidentToDate 2024-06-18 22:31:48 for CaseMasterID 51
Warning: CrimeRegisteredDate 2021-02-27 00:00:00 is before one day after IncidentFromDate 2021-02-27 08:33:01 for CaseMasterID 52
Warning: CrimeRegisteredDate 2021-02-27 00:00:00 is before one day after IncidentToDate 2021-02-27 08:39:01 for CaseMasterID 52
Warning: CrimeRegisteredDate 2025-01-16 00:00:00 is before one day after IncidentFromDate 2025-01-16 13:11:58 for CaseMasterID 53
Warning: CrimeRegisteredDate 2025-01-16 00:00:00 is before one day after IncidentToDate 2025-01-16 13:45:58 for CaseMasterID 53
Warning: CrimeRegisteredDate 2025-04-26 00:00:00 is before one day after IncidentFromDate 2025-04-26 00:57:21 for CaseMasterID 54
Warning: CrimeRegisteredDate 2025-04-26 00:00:00 is before one day after IncidentToDate 2025-04-27 08:16:03 for CaseMasterID 54
Warning: CrimeRegisteredDate 2024-07-10 00:00:00 is before one day after IncidentFromDate 2024-07-10 20:37:22 for CaseMasterID 55
Warning: CrimeRegisteredDate 2024-07-10 00:00:00 is before one day after IncidentToDate 2024-07-10 20:53:22 for CaseMasterID 55
Warning: CrimeRegisteredDate 2025-10-31 00:00:00 is before one day after IncidentFromDate 2025-11-01 02:14:31 for CaseMasterID 56
Warning: CrimeRegisteredDate 2025-10-31 00:00:00 is before one day after IncidentToDate 2025-11-01 02:41:31 for CaseMasterID 56
Warning: CrimeRegisteredDate 2025-10-26 00:00:00 is before one day after IncidentFromDate 2025-10-27 10:03:29 for CaseMasterID 57
Warning: CrimeRegisteredDate 2025-10-26 00:00:00 is before one day after IncidentToDate 2025-10-27 10:24:29 for CaseMasterID 57
Warning: CrimeRegisteredDate 2025-10-28 00:00:00 is before one day after IncidentFromDate 2025-10-29 02:16:13 for CaseMasterID 59
Warning: CrimeRegisteredDate 2025-10-28 00:00:00 is before one day after IncidentToDate 2025-10-29 02:56:13 for CaseMasterID 59
Warning: CrimeRegisteredDate 2025-06-21 00:00:00 is before one day after IncidentFromDate 2025-06-21 06:39:27 for CaseMasterID 60
Warning: CrimeRegisteredDate 2025-06-21 00:00:00 is before one day after IncidentToDate 2025-06-21 07:18:27 for CaseMasterID 60
Warning: CrimeRegisteredDate 2025-06-19 00:00:00 is before one day after IncidentFromDate 2025-06-19 08:52:13 for CaseMasterID 62
Warning: CrimeRegisteredDate 2025-06-19 00:00:00 is before one day after IncidentToDate 2025-06-19 08:55:13 for CaseMasterID 62
Warning: CrimeRegisteredDate 2022-06-29 00:00:00 is before one day after IncidentFromDate 2022-06-30 17:27:28 for CaseMasterID 63
Warning: CrimeRegisteredDate 2022-06-29 00:00:00 is before one day after IncidentToDate 2022-06-30 17:31:28 for CaseMasterID 63
Warning: CrimeRegisteredDate 2021-05-01 00:00:00 is before one day after IncidentFromDate 2021-05-01 10:06:42 for CaseMasterID 64
Warning: CrimeRegisteredDate 2021-05-01 00:00:00 is before one day after IncidentToDate 2021-05-01 10:51:42 for CaseMasterID 64
Warning: CrimeRegisteredDate 2022-10-10 00:00:00 is before one day after IncidentFromDate 2022-10-10 08:41:36 for CaseMasterID 67
Warning: CrimeRegisteredDate 2022-10-10 00:00:00 is before one day after IncidentToDate 2022-10-10 09:17:36 for CaseMasterID 67
Warning: CrimeRegisteredDate 2025-10-11 00:00:00 is before one day after IncidentFromDate 2025-10-12 09:24:14 for CaseMasterID 69
Warning: CrimeRegisteredDate 2025-10-11 00:00:00 is before one day after IncidentToDate 2025-10-12 10:09:14 for CaseMasterID 69
Warning: CrimeRegisteredDate 2022-09-01 00:00:00 is before one day after IncidentFromDate 2022-09-02 07:12:55 for CaseMasterID 70
Warning: CrimeRegisteredDate 2022-09-01 00:00:00 is before one day after IncidentToDate 2022-09-02 07:17:55 for CaseMasterID 70
Warning: CrimeRegisteredDate 2025-12-02 00:00:00 is before one day after IncidentFromDate 2025-12-03 15:08:58 for CaseMasterID 71
Warning: CrimeRegisteredDate 2025-12-02 00:00:00 is before one day after IncidentToDate 2025-12-03 15:11:58 for CaseMasterID 71
Warning: CrimeRegisteredDate 2023-03-10 00:00:00 is before one day after IncidentFromDate 2023-03-10 16:22:48 for CaseMasterID 72
Warning: CrimeRegisteredDate 2023-03-10 00:00:00 is before one day after IncidentToDate 2023-03-10 17:44:11 for CaseMasterID 72
Warning: CrimeRegisteredDate 2022-12-10 00:00:00 is before one day after IncidentFromDate 2022-12-10 20:50:44 for CaseMasterID 73
Warning: CrimeRegisteredDate 2022-12-10 00:00:00 is before one day after IncidentToDate 2022-12-10 20:52:44 for CaseMasterID 73
Warning: CrimeRegisteredDate 2025-11-15 00:00:00 is before one day after IncidentToDate 2025-11-17 13:36:41 for CaseMasterID 74
Warning: CrimeRegisteredDate 2024-02-18 00:00:00 is before one day after IncidentFromDate 2024-02-18 04:32:57 for CaseMasterID 75
Warning: CrimeRegisteredDate 2024-02-18 00:00:00 is before one day after IncidentToDate 2024-02-18 04:53:57 for CaseMasterID 75
Warning: CrimeRegisteredDate 2025-02-16 00:00:00 is before one day after IncidentFromDate 2025-02-16 03:03:16 for CaseMasterID 76
Warning: CrimeRegisteredDate 2025-02-16 00:00:00 is before one day after IncidentToDate 2025-02-16 03:11:16 for CaseMasterID 76
Warning: CrimeRegisteredDate 2022-10-05 00:00:00 is before one day after IncidentFromDate 2022-10-05 06:56:32 for CaseMasterID 79
Warning: CrimeRegisteredDate 2022-10-05 00:00:00 is before one day after IncidentToDate 2022-10-05 06:58:32 for CaseMasterID 79
Warning: CrimeRegisteredDate 2024-05-02 00:00:00 is before one day after IncidentFromDate 2024-05-02 23:40:17 for CaseMasterID 80
Warning: CrimeRegisteredDate 2024-05-02 00:00:00 is before one day after IncidentToDate 2024-05-03 00:00:17 for CaseMasterID 80
Warning: CrimeRegisteredDate 2023-11-24 00:00:00 is before one day after IncidentFromDate 2023-11-24 08:50:42 for CaseMasterID 81
Warning: CrimeRegisteredDate 2023-11-24 00:00:00 is before one day after IncidentToDate 2023-11-25 09:53:53 for CaseMasterID 81
Warning: CrimeRegisteredDate 2024-10-26 00:00:00 is before one day after IncidentFromDate 2024-10-27 06:01:30 for CaseMasterID 83
Warning: CrimeRegisteredDate 2024-10-26 00:00:00 is before one day after IncidentToDate 2024-10-27 06:09:30 for CaseMasterID 83
Warning: CrimeRegisteredDate 2022-10-31 00:00:00 is before one day after IncidentFromDate 2022-10-31 22:53:38 for CaseMasterID 84
Warning: CrimeRegisteredDate 2022-10-31 00:00:00 is before one day after IncidentToDate 2022-10-31 23:11:38 for CaseMasterID 84
Warning: CrimeRegisteredDate 2024-03-26 00:00:00 is before one day after IncidentFromDate 2024-03-26 02:02:27 for CaseMasterID 85
Warning: CrimeRegisteredDate 2024-03-26 00:00:00 is before one day after IncidentToDate 2024-03-26 02:27:27 for CaseMasterID 85
Warning: CrimeRegisteredDate 2021-06-11 00:00:00 is before one day after IncidentFromDate 2021-06-11 18:37:16 for CaseMasterID 86
Warning: CrimeRegisteredDate 2021-06-11 00:00:00 is before one day after IncidentToDate 2021-06-11 19:07:16 for CaseMasterID 86
Warning: CrimeRegisteredDate 2024-10-02 00:00:00 is before one day after IncidentFromDate 2024-10-02 12:48:54 for CaseMasterID 87
Warning: CrimeRegisteredDate 2024-10-02 00:00:00 is before one day after IncidentToDate 2024-10-02 12:48:54 for CaseMasterID 87
Warning: CrimeRegisteredDate 2024-10-07 00:00:00 is before one day after IncidentFromDate 2024-10-07 21:04:58 for CaseMasterID 92
Warning: CrimeRegisteredDate 2024-10-07 00:00:00 is before one day after IncidentToDate 2024-10-07 21:09:58 for CaseMasterID 92
Warning: CrimeRegisteredDate 2021-09-29 00:00:00 is before one day after IncidentFromDate 2021-09-29 21:34:48 for CaseMasterID 93
Warning: CrimeRegisteredDate 2021-09-29 00:00:00 is before one day after IncidentToDate 2021-09-29 21:44:48 for CaseMasterID 93
Warning: CrimeRegisteredDate 2022-05-14 00:00:00 is before one day after IncidentFromDate 2022-05-14 07:46:00 for CaseMasterID 94
Warning: CrimeRegisteredDate 2022-05-14 00:00:00 is before one day after IncidentToDate 2022-05-14 08:04:00 for CaseMasterID 94
Warning: CrimeRegisteredDate 2022-10-30 00:00:00 is before one day after IncidentFromDate 2022-10-30 21:07:36 for CaseMasterID 95
Warning: CrimeRegisteredDate 2022-10-30 00:00:00 is before one day after IncidentToDate 2022-10-30 21:30:36 for CaseMasterID 95
Warning: CrimeRegisteredDate 2024-11-20 00:00:00 is before one day after IncidentFromDate 2024-11-20 22:18:50 for CaseMasterID 96
Warning: CrimeRegisteredDate 2024-11-20 00:00:00 is before one day after IncidentToDate 2024-11-20 22:22:50 for CaseMasterID 96
Warning: CrimeRegisteredDate 2024-02-03 00:00:00 is before one day after IncidentFromDate 2024-02-03 06:22:47 for CaseMasterID 97
Warning: CrimeRegisteredDate 2024-02-03 00:00:00 is before one day after IncidentToDate 2024-02-03 06:54:47 for CaseMasterID 97
Warning: CrimeRegisteredDate 2025-03-16 00:00:00 is before one day after IncidentFromDate 2025-03-16 00:12:17 for CaseMasterID 98
Warning: CrimeRegisteredDate 2025-03-16 00:00:00 is before one day after IncidentToDate 2025-03-17 09:58:16 for CaseMasterID 98
Warning: CrimeRegisteredDate 2021-06-12 00:00:00 is before one day after IncidentFromDate 2021-06-13 01:23:42 for CaseMasterID 99
Warning: CrimeRegisteredDate 2021-06-12 00:00:00 is before one day after IncidentToDate 2021-06-13 01:50:42 for CaseMasterID 99
Warning: CrimeRegisteredDate 2023-02-12 00:00:00 is before one day after IncidentFromDate 2023-02-12 08:15:33 for CaseMasterID 100
Warning: CrimeRegisteredDate 2023-02-12 00:00:00 is before one day after IncidentToDate 2023-02-12 08:57:33 for CaseMasterID 100
Warning: CrimeRegisteredDate 2024-07-15 00:00:00 is before one day after IncidentFromDate 2024-07-15 15:38:59 for CaseMasterID 101
Warning: CrimeRegisteredDate 2024-07-15 00:00:00 is before one day after IncidentToDate 2024-07-15 15:52:59 for CaseMasterID 101
Warning: CrimeRegisteredDate 2021-04-27 00:00:00 is before one day after IncidentFromDate 2021-04-28 17:22:42 for CaseMasterID 102
Warning: CrimeRegisteredDate 2021-04-27 00:00:00 is before one day after IncidentToDate 2021-04-28 18:06:42 for CaseMasterID 102
Warning: CrimeRegisteredDate 2022-11-18 00:00:00 is before one day after IncidentFromDate 2022-11-18 02:17:31 for CaseMasterID 103
Warning: CrimeRegisteredDate 2022-11-18 00:00:00 is before one day after IncidentToDate 2022-11-18 02:21:31 for CaseMasterID 103
Warning: CrimeRegisteredDate 2021-12-13 00:00:00 is before one day after IncidentFromDate 2021-12-14 00:36:12 for CaseMasterID 107
Warning: CrimeRegisteredDate 2021-12-13 00:00:00 is before one day after IncidentToDate 2021-12-14 00:49:12 for CaseMasterID 107
Warning: CrimeRegisteredDate 2023-07-26 00:00:00 is before one day after IncidentFromDate 2023-07-27 09:20:45 for CaseMasterID 108
Warning: CrimeRegisteredDate 2023-07-26 00:00:00 is before one day after IncidentToDate 2023-07-27 09:28:45 for CaseMasterID 108
Warning: CrimeRegisteredDate 2022-11-01 00:00:00 is before one day after IncidentToDate 2022-11-01 00:21:53 for CaseMasterID 109
Warning: CrimeRegisteredDate 2026-01-26 00:00:00 is before one day after IncidentFromDate 2026-01-26 05:15:53 for CaseMasterID 111
Warning: CrimeRegisteredDate 2026-01-26 00:00:00 is before one day after IncidentToDate 2026-01-26 05:40:53 for CaseMasterID 111
Warning: CrimeRegisteredDate 2023-05-11 00:00:00 is before one day after IncidentFromDate 2023-05-11 13:27:14 for CaseMasterID 113
Warning: CrimeRegisteredDate 2023-05-11 00:00:00 is before one day after IncidentToDate 2023-05-13 23:34:25 for CaseMasterID 113
Warning: CrimeRegisteredDate 2025-05-26 00:00:00 is before one day after IncidentFromDate 2025-05-26 04:33:48 for CaseMasterID 114
Warning: CrimeRegisteredDate 2025-05-26 00:00:00 is before one day after IncidentToDate 2025-05-26 04:51:48 for CaseMasterID 114
Warning: CrimeRegisteredDate 2023-10-07 00:00:00 is before one day after IncidentFromDate 2023-10-08 04:25:38 for CaseMasterID 115

In [64]:
## Just to check if the ArrestSurrender dataframe's ArrestSurrenderDate is after the CrimeRegisteredDate in CaseMaster dataframe
for index, row in ArrestSurrender.iterrows():
    case_id = row['CaseMasterID']
    arrest_date = row['ArrestSurrenderDate']
    crime_date = CaseMaster.loc[CaseMaster['CaseMasterID'] == case_id, 'CrimeRegisteredDate'].values[0]
    one_day_after_crime_date = crime_date + pd.Timedelta(days=1)

    if pd.notnull(arrest_date) and pd.notnull(crime_date) and arrest_date < one_day_after_crime_date:
        print(f"Warning: ArrestSurrenderDate {arrest_date} is before one day after CrimeRegisteredDate {one_day_after_crime_date} for CaseMasterID {case_id}")

Warning: ArrestSurrenderDate 2023-06-26 00:00:00 is before one day after CrimeRegisteredDate 2023-06-27 00:00:00 for CaseMasterID 8
Warning: ArrestSurrenderDate 2023-06-26 00:00:00 is before one day after CrimeRegisteredDate 2023-06-27 00:00:00 for CaseMasterID 8
Warning: ArrestSurrenderDate 2022-07-14 00:00:00 is before one day after CrimeRegisteredDate 2022-07-15 00:00:00 for CaseMasterID 9
Warning: ArrestSurrenderDate 2022-12-18 00:00:00 is before one day after CrimeRegisteredDate 2022-12-19 00:00:00 for CaseMasterID 25
Warning: ArrestSurrenderDate 2023-10-05 00:00:00 is before one day after CrimeRegisteredDate 2023-10-06 00:00:00 for CaseMasterID 33
Warning: ArrestSurrenderDate 2024-06-17 00:00:00 is before one day after CrimeRegisteredDate 2024-06-18 00:00:00 for CaseMasterID 39
Warning: ArrestSurrenderDate 2025-09-23 00:00:00 is before one day after CrimeRegisteredDate 2025-09-24 00:00:00 for CaseMasterID 41
Warning: ArrestSurrenderDate 2025-10-27 00:00:00 is before one day after CrimeRegisteredDate 2025-10-28 00:00:00 for CaseMasterID 44
Warning: ArrestSurrenderDate 2023-05-31 00:00:00 is before one day after CrimeRegisteredDate 2023-06-01 00:00:00 for CaseMasterID 61
Warning: ArrestSurrenderDate 2025-02-16 00:00:00 is before one day after CrimeRegisteredDate 2025-02-17 00:00:00 for CaseMasterID 76
Warning: ArrestSurrenderDate 2022-04-15 00:00:00 is before one day after CrimeRegisteredDate 2022-04-16 00:00:00 for CaseMasterID 78
Warning: ArrestSurrenderDate 2022-10-05 00:00:00 is before one day after CrimeRegisteredDate 2022-10-06 00:00:00 for CaseMasterID 79
Warning: ArrestSurrenderDate 2022-10-05 00:00:00 is before one day after CrimeRegisteredDate 2022-10-06 00:00:00 for CaseMasterID 79
Warning: ArrestSurrenderDate 2024-10-26 00:00:00 is before one day after CrimeRegisteredDate 2024-10-27 00:00:00 for CaseMasterID 83
Warning: ArrestSurrenderDate 2022-10-30 00:00:00 is before one day after CrimeRegisteredDate 2022-10-31 00:00:00 for CaseMasterID 95
Warning: ArrestSurrenderDate 2025-03-16 00:00:00 is before one day after CrimeRegisteredDate 2025-03-17 00:00:00 for CaseMasterID 98
Warning: ArrestSurrenderDate 2025-02-06 00:00:00 is before one day after CrimeRegisteredDate 2025-02-07 00:00:00 for CaseMasterID 130
Warning: ArrestSurrenderDate 2022-10-11 00:00:00 is before one day after CrimeRegisteredDate 2022-10-12 00:00:00 for CaseMasterID 138
Warning: ArrestSurrenderDate 2023-08-08 00:00:00 is before one day after CrimeRegisteredDate 2023-08-09 00:00:00 for CaseMasterID 145
Warning: ArrestSurrenderDate 2021-10-21 00:00:00 is before one day after CrimeRegisteredDate 2021-10-22 00:00:00 for CaseMasterID 150
Warning: ArrestSurrenderDate 2025-10-23 00:00:00 is before one day after CrimeRegisteredDate 2025-10-24 00:00:00 for CaseMasterID 152
Warning: ArrestSurrenderDate 2023-03-21 00:00:00 is before one day after CrimeRegisteredDate 2023-03-22 00:00:00 for CaseMasterID 173
Warning: ArrestSurrenderDate 2025-01-20 00:00:00 is before one day after CrimeRegisteredDate 2025-01-21 00:00:00 for CaseMasterID 188
Warning: ArrestSurrenderDate 2021-11-07 00:00:00 is before one day after CrimeRegisteredDate 2021-11-08 00:00:00 for CaseMasterID 190
Warning: ArrestSurrenderDate 2024-11-10 00:00:00 is before one day after CrimeRegisteredDate 2024-11-11 00:00:00 for CaseMasterID 193
Warning: ArrestSurrenderDate 2023-10-26 00:00:00 is before one day after CrimeRegisteredDate 2023-10-27 00:00:00 for CaseMasterID 195
Warning: ArrestSurrenderDate 2021-08-25 00:00:00 is before one day after CrimeRegisteredDate 2021-08-26 00:00:00 for CaseMasterID 197
Warning: ArrestSurrenderDate 2022-09-17 00:00:00 is before one day after CrimeRegisteredDate 2022-09-18 00:00:00 for CaseMasterID 230
Warning: ArrestSurrenderDate 2026-05-09 00:00:00 is before one day after CrimeRegisteredDate 2026-05-10 00:00:00 for CaseMasterID 238
Warning: ArrestSurrenderDate 2024-10-01 00:00:00 is before one day after CrimeRegisteredDate 2024-10-02 00:00:00 for CaseMasterID 251
Warning: ArrestSurrenderDate 2024-10-01 00:00:00 is before one day after CrimeRegisteredDate 2024-10-02 00:00:00 for CaseMasterID 251
Warning: ArrestSurrenderDate 2025-07-20 00:00:00 is before one day after CrimeRegisteredDate 2025-07-21 00:00:00 for CaseMasterID 259
Warning: ArrestSurrenderDate 2022-09-11 00:00:00 is before one day after CrimeRegisteredDate 2022-09-12 00:00:00 for CaseMasterID 260
Warning: ArrestSurrenderDate 2022-09-11 00:00:00 is before one day after CrimeRegisteredDate 2022-09-12 00:00:00 for CaseMasterID 260
Warning: ArrestSurrenderDate 2022-10-25 00:00:00 is before one day after CrimeRegisteredDate 2022-10-26 00:00:00 for CaseMasterID 262
Warning: ArrestSurrenderDate 2026-06-05 00:00:00 is before one day after CrimeRegisteredDate 2026-06-06 00:00:00 for CaseMasterID 274
Warning: ArrestSurrenderDate 2026-05-30 00:00:00 is before one day after CrimeRegisteredDate 2026-05-31 00:00:00 for CaseMasterID 276
Warning: ArrestSurrenderDate 2022-06-22 00:00:00 is before one day after CrimeRegisteredDate 2022-06-23 00:00:00 for CaseMasterID 292
Warning: ArrestSurrenderDate 2022-10-02 00:00:00 is before one day after CrimeRegisteredDate 2022-10-03 00:00:00 for CaseMasterID 306
Warning: ArrestSurrenderDate 2024-08-28 00:00:00 is before one day after CrimeRegisteredDate 2024-08-29 00:00:00 for CaseMasterID 312
Warning: ArrestSurrenderDate 2021-08-23 00:00:00 is before one day after CrimeRegisteredDate 2021-08-24 00:00:00 for CaseMasterID 320
Warning: ArrestSurrenderDate 2026-07-13 00:00:00 is before one day after CrimeRegisteredDate 2026-07-14 00:00:00 for CaseMasterID 321
Warning: ArrestSurrenderDate 2025-10-07 00:00:00 is before one day after CrimeRegisteredDate 2025-10-08 00:00:00 for CaseMasterID 323
Warning: ArrestSurrenderDate 2023-08-15 00:00:00 is before one day after CrimeRegisteredDate 2023-08-16 00:00:00 for CaseMasterID 326
Warning: ArrestSurrenderDate 2022-03-01 00:00:00 is before one day after CrimeRegisteredDate 2022-03-02 00:00:00 for CaseMasterID 338
Warning: ArrestSurrenderDate 2022-03-01 00:00:00 is before one day after CrimeRegisteredDate 2022-03-02 00:00:00 for CaseMasterID 338
Warning: ArrestSurrenderDate 2025-05-22 00:00:00 is before one day after CrimeRegisteredDate 2025-05-23 00:00:00 for CaseMasterID 341
Warning: ArrestSurrenderDate 2023-03-26 00:00:00 is before one day after CrimeRegisteredDate 2023-03-27 00:00:00 for CaseMasterID 354
Warning: ArrestSurrenderDate 2024-02-18 00:00:00 is before one day after CrimeRegisteredDate 2024-02-19 00:00:00 for CaseMasterID 355
Warning: ArrestSurrenderDate 2022-09-16 00:00:00 is before one day after CrimeRegisteredDate 2022-09-17 00:00:00 for CaseMasterID 376
Warning: ArrestSurrenderDate 2022-11-11 00:00:00 is before one day after CrimeRegisteredDate 2022-11-12 00:00:00 for CaseMasterID 393
Warning: ArrestSurrenderDate 2025-09-18 00:00:00 is before one day after CrimeRegisteredDate 2025-09-19 00:00:00 for CaseMasterID 397
Warning: ArrestSurrenderDate 2026-03-01 00:00:00 is before one day after CrimeRegisteredDate 2026-03-02 00:00:00 for CaseMasterID 401
Warning: ArrestSurrenderDate 2025-04-01 00:00:00 is before one day after CrimeRegisteredDate 2025-04-02 00:00:00 for CaseMasterID 419
Warning: ArrestSurrenderDate 2025-04-01 00:00:00 is before one day after CrimeRegisteredDate 2025-04-02 00:00:00 for CaseMasterID 419
Warning: ArrestSurrenderDate 2025-08-01 00:00:00 is before one day after CrimeRegisteredDate 2025-08-02 00:00:00 for CaseMasterID 420
Warning: ArrestSurrenderDate 2023-01-12 00:00:00 is before one day after CrimeRegisteredDate 2023-01-13 00:00:00 for CaseMasterID 421
Warning: ArrestSurrenderDate 2024-12-09 00:00:00 is before one day after CrimeRegisteredDate 2024-12-10 00:00:00 for CaseMasterID 423
Warning: ArrestSurrenderDate 2026-02-26 00:00:00 is before one day after CrimeRegisteredDate 2026-02-27 00:00:00 for CaseMasterID 441
Warning: ArrestSurrenderDate 2025-03-02 00:00:00 is before one day after CrimeRegisteredDate 2025-03-03 00:00:00 for CaseMasterID 446
Warning: ArrestSurrenderDate 2021-12-31 00:00:00 is before one day after CrimeRegisteredDate 2022-01-01 00:00:00 for CaseMasterID 450
Warning: ArrestSurrenderDate 2024-09-14 00:00:00 is before one day after CrimeRegisteredDate 2024-09-15 00:00:00 for CaseMasterID 457
Warning: ArrestSurrenderDate 2023-12-19 00:00:00 is before one day after CrimeRegisteredDate 2023-12-20 00:00:00 for CaseMasterID 458
Warning: ArrestSurrenderDate 2023-12-19 00:00:00 is before one day after CrimeRegisteredDate 2023-12-20 00:00:00 for CaseMasterID 458
Warning: ArrestSurrenderDate 2021-08-22 00:00:00 is before one day after CrimeRegisteredDate 2021-08-23 00:00:00 for CaseMasterID 463
Warning: ArrestSurrenderDate 2024-02-07 00:00:00 is before one day after CrimeRegisteredDate 2024-02-08 00:00:00 for CaseMasterID 471
Warning: ArrestSurrenderDate 2024-02-07 00:00:00 is before one day after CrimeRegisteredDate 2024-02-08 00:00:00 for CaseMasterID 471
Warning: ArrestSurrenderDate 2025-11-05 00:00:00 is before one day after CrimeRegisteredDate 2025-11-06 00:00:00 for CaseMasterID 476
Warning: ArrestSurrenderDate 2025-08-22 00:00:00 is before one day after CrimeRegisteredDate 2025-08-23 00:00:00 for CaseMasterID 480
Warning: ArrestSurrenderDate 2026-01-26 00:00:00 is before one day after CrimeRegisteredDate 2026-01-27 00:00:00 for CaseMasterID 498
Warning: ArrestSurrenderDate 2026-01-26 00:00:00 is before one day after CrimeRegisteredDate 2026-01-27 00:00:00 for CaseMasterID 498
Warning: ArrestSurrenderDate 2023-10-05 00:00:00 is before one day after CrimeRegisteredDate 2023-10-06 00:00:00 for CaseMasterID 500
Warning: ArrestSurrenderDate 2022-04-21 00:00:00 is before one day after CrimeRegisteredDate 2022-04-22 00:00:00 for CaseMasterID 503
Warning: ArrestSurrenderDate 2025-09-05 00:00:00 is before one day after CrimeRegisteredDate 2025-09-06 00:00:00 for CaseMasterID 510
Warning: ArrestSurrenderDate 2025-09-05 00:00:00 is before one day after CrimeRegisteredDate 2025-09-06 00:00:00 for CaseMasterID 510
Warning: ArrestSurrenderDate 2023-01-05 00:00:00 is before one day after CrimeRegisteredDate 2023-01-06 00:00:00 for CaseMasterID 511
Warning: ArrestSurrenderDate 2021-01-01 00:00:00 is before one day after CrimeRegisteredDate 2021-01-02 00:00:00 for CaseMasterID 522
Warning: ArrestSurrenderDate 2022-11-06 00:00:00 is before one day after CrimeRegisteredDate 2022-11-07 00:00:00 for CaseMasterID 523
Warning: ArrestSurrenderDate 2024-08-07 00:00:00 is before one day after CrimeRegisteredDate 2024-08-08 00:00:00 for CaseMasterID 530
Warning: ArrestSurrenderDate 2023-11-16 00:00:00 is before one day after CrimeRegisteredDate 2023-11-17 00:00:00 for CaseMasterID 533
Warning: ArrestSurrenderDate 2023-05-30 00:00:00 is before one day after CrimeRegisteredDate 2023-05-31 00:00:00 for CaseMasterID 536
Warning: ArrestSurrenderDate 2025-03-18 00:00:00 is before one day after CrimeRegisteredDate 2025-03-19 00:00:00 for CaseMasterID 546
Warning: ArrestSurrenderDate 2025-04-20 00:00:00 is before one day after CrimeRegisteredDate 2025-04-21 00:00:00 for CaseMasterID 549
Warning: ArrestSurrenderDate 2022-03-07 00:00:00 is before one day after CrimeRegisteredDate 2022-03-08 00:00:00 for CaseMasterID 551
Warning: ArrestSurrenderDate 2022-05-16 00:00:00 is before one day after CrimeRegisteredDate 2022-05-17 00:00:00 for CaseMasterID 559
Warning: ArrestSurrenderDate 2022-04-09 00:00:00 is before one day after CrimeRegisteredDate 2022-04-10 00:00:00 for CaseMasterID 584
Warning: ArrestSurrenderDate 2022-04-09 00:00:00 is before one day after CrimeRegisteredDate 2022-04-10 00:00:00 for CaseMasterID 584
Warning: ArrestSurrenderDate 2022-10-16 00:00:00 is before one day after CrimeRegisteredDate 2022-10-17 00:00:00 for CaseMasterID 585
Warning: ArrestSurrenderDate 2025-07-21 00:00:00 is before one day after CrimeRegisteredDate 2025-07-22 00:00:00 for CaseMasterID 590
Warning: ArrestSurrenderDate 2024-06-22 00:00:00 is before one day after CrimeRegisteredDate 2024-06-23 00:00:00 for CaseMasterID 595
Warning: ArrestSurrenderDate 2026-06-26 00:00:00 is before one day after CrimeRegisteredDate 2026-06-27 00:00:00 for CaseMasterID 596
Warning: ArrestSurrenderDate 2024-01-10 00:00:00 is before one day after CrimeRegisteredDate 2024-01-11 00:00:00 for CaseMasterID 605
Warning: ArrestSurrenderDate 2022-10-31 00:00:00 is before one day after CrimeRegisteredDate 2022-11-01 00:00:00 for CaseMasterID 606
Warning: ArrestSurrenderDate 2024-02-11 00:00:00 is before one day after CrimeRegisteredDate 2024-02-12 00:00:00 for CaseMasterID 614
Warning: ArrestSurrenderDate 2025-04-04 00:00:00 is before one day after CrimeRegisteredDate 2025-04-05 00:00:00 for CaseMasterID 634
Warning: ArrestSurrenderDate 2025-06-16 00:00:00 is before one day after CrimeRegisteredDate 2025-06-17 00:00:00 for CaseMasterID 636
Warning: ArrestSurrenderDate 2023-09-06 00:00:00 is before one day after CrimeRegisteredDate 2023-09-07 00:00:00 for CaseMasterID 644
Warning: ArrestSurrenderDate 2024-06-03 00:00:00 is before one day after CrimeRegisteredDate 2024-06-04 00:00:00 for CaseMasterID 655
Warning: ArrestSurrenderDate 2024-09-29 00:00:00 is before one day after CrimeRegisteredDate 2024-09-30 00:00:00 for CaseMasterID 662
Warning: ArrestSurrenderDate 2022-02-02 00:00:00 is before one day after CrimeRegisteredDate 2022-02-03 00:00:00 for CaseMasterID 666
Warning: ArrestSurrenderDate 2024-09-03 00:00:00 is before one day after CrimeRegisteredDate 2024-09-04 00:00:00 for CaseMasterID 670
Warning: ArrestSurrenderDate 2021-06-09 00:00:00 is before one day after CrimeRegisteredDate 2021-06-10 00:00:00 for CaseMasterID 689
Warning: ArrestSurrenderDate 2021-06-09 00:00:00 is before one day after CrimeRegisteredDate 2021-06-10 00:00:00 for CaseMasterID 689
Warning: ArrestSurrenderDate 2026-07-16 00:00:00 is before one day after CrimeRegisteredDate 2026-07-17 00:00:00 for CaseMasterID 692
Warning: ArrestSurrenderDate 2025-02-01 00:00:00 is before one day after CrimeRegisteredDate 2025-02-02 00:00:00 for CaseMasterID 696
Warning: ArrestSurrenderDate 2024-12-21 00:00:00 is before one day after CrimeRegisteredDate 2024-12-22 00:00:00 for CaseMasterID 707
Warning: ArrestSurrenderDate 2025-05-06 00:00:00 is before one day after CrimeRegisteredDate 2025-05-07 00:00:00 for CaseMasterID 711
Warning: ArrestSurrenderDate 2025-07-15 00:00:00 is before one day after CrimeRegisteredDate 2025-07-16 00:00:00 for CaseMasterID 712
Warning: ArrestSurrenderDate 2025-07-15 00:00:00 is before one day after CrimeRegisteredDate 2025-07-16 00:00:00 for CaseMasterID 712
Warning: ArrestSurrenderDate 2025-03-21 00:00:00 is before one day after CrimeRegisteredDate 2025-03-22 00:00:00 for CaseMasterID 713
Warning: ArrestSurrenderDate 2022-10-05 00:00:00 is before one day after CrimeRegisteredDate 2022-10-06 00:00:00 for CaseMasterID 714
Warning: ArrestSurrenderDate 2025-01-30 00:00:00 is before one day after CrimeRegisteredDate 2025-01-31 00:00:00 for CaseMasterID 716
Warning: ArrestSurrenderDate 2025-02-01 00:00:00 is before one day after CrimeRegisteredDate 2025-02-02 00:00:00 for CaseMasterID 719
Warning: ArrestSurrenderDate 2024-12-03 00:00:00 is before one day after CrimeRegisteredDate 2024-12-04 00:00:00 for CaseMasterID 765
Warning: ArrestSurrenderDate 2022-05-20 00:00:00 is before one day after CrimeRegisteredDate 2022-05-21 00:00:00 for CaseMasterID 770
Warning: ArrestSurrenderDate 2021-06-14 00:00:00 is before one day after CrimeRegisteredDate 2021-06-15 00:00:00 for CaseMasterID 771
Warning: ArrestSurrenderDate 2025-09-26 00:00:00 is before one day after CrimeRegisteredDate 2025-09-27 00:00:00 for CaseMasterID 772
Warning: ArrestSurrenderDate 2024-09-16 00:00:00 is before one day after CrimeRegisteredDate 2024-09-17 00:00:00 for CaseMasterID 777
Warning: ArrestSurrenderDate 2023-10-11 00:00:00 is before one day after CrimeRegisteredDate 2023-10-12 00:00:00 for CaseMasterID 789
Warning: ArrestSurrenderDate 2026-03-26 00:00:00 is before one day after CrimeRegisteredDate 2026-03-27 00:00:00 for CaseMasterID 797
Warning: ArrestSurrenderDate 2021-06-20 00:00:00 is before one day after CrimeRegisteredDate 2021-06-21 00:00:00 for CaseMasterID 800
Warning: ArrestSurrenderDate 2023-12-19 00:00:00 is before one day after CrimeRegisteredDate 2023-12-20 00:00:00 for CaseMasterID 809
Warning: ArrestSurrenderDate 2023-12-19 00:00:00 is before one day after CrimeRegisteredDate 2023-12-20 00:00:00 for CaseMasterID 809
Warning: ArrestSurrenderDate 2026-06-24 00:00:00 is before one day after CrimeRegisteredDate 2026-06-25 00:00:00 for CaseMasterID 844
Warning: ArrestSurrenderDate 2026-02-18 00:00:00 is before one day after CrimeRegisteredDate 2026-02-19 00:00:00 for CaseMasterID 845
Warning: ArrestSurrenderDate 2024-05-11 00:00:00 is before one day after CrimeRegisteredDate 2024-05-12 00:00:00 for CaseMasterID 868
Warning: ArrestSurrenderDate 2026-07-01 00:00:00 is before one day after CrimeRegisteredDate 2026-07-02 00:00:00 for CaseMasterID 869
Warning: ArrestSurrenderDate 2021-11-09 00:00:00 is before one day after CrimeRegisteredDate 2021-11-10 00:00:00 for CaseMasterID 890
Warning: ArrestSurrenderDate 2021-11-13 00:00:00 is before one day after CrimeRegisteredDate 2021-11-14 00:00:00 for CaseMasterID 894
Warning: ArrestSurrenderDate 2022-01-15 00:00:00 is before one day after CrimeRegisteredDate 2022-01-16 00:00:00 for CaseMasterID 909
Warning: ArrestSurrenderDate 2022-10-24 00:00:00 is before one day after CrimeRegisteredDate 2022-10-25 00:00:00 for CaseMasterID 913
Warning: ArrestSurrenderDate 2025-12-15 00:00:00 is before one day after CrimeRegisteredDate 2025-12-16 00:00:00 for CaseMasterID 914
Warning: ArrestSurrenderDate 2023-11-18 00:00:00 is before one day after CrimeRegisteredDate 2023-11-19 00:00:00 for CaseMasterID 920
Warning: ArrestSurrenderDate 2026-04-10 00:00:00 is before one day after CrimeRegisteredDate 2026-04-11 00:00:00 for CaseMasterID 925
Warning: ArrestSurrenderDate 2021-12-25 00:00:00 is before one day after CrimeRegisteredDate 2021-12-26 00:00:00 for CaseMasterID 929
Warning: ArrestSurrenderDate 2024-05-21 00:00:00 is before one day after CrimeRegisteredDate 2024-05-22 00:00:00 for CaseMasterID 939
Warning: ArrestSurrenderDate 2024-01-31 00:00:00 is before one day after CrimeRegisteredDate 2024-02-01 00:00:00 for CaseMasterID 940
Warning: ArrestSurrenderDate 2021-04-24 00:00:00 is before one day after CrimeRegisteredDate 2021-04-25 00:00:00 for CaseMasterID 944
Warning: ArrestSurrenderDate 2022-03-21 00:00:00 is before one day after CrimeRegisteredDate 2022-03-22 00:00:00 for CaseMasterID 946
Warning: ArrestSurrenderDate 2021-05-09 00:00:00 is before one day after CrimeRegisteredDate 2021-05-10 00:00:00 for CaseMasterID 949
Warning: ArrestSurrenderDate 2022-11-09 00:00:00 is before one day after CrimeRegisteredDate 2022-11-10 00:00:00 for CaseMasterID 980
Warning: ArrestSurrenderDate 2021-06-13 00:00:00 is before one day after CrimeRegisteredDate 2021-06-14 00:00:00 for CaseMasterID 988
Warning: ArrestSurrenderDate 2021-06-13 00:00:00 is before one day after CrimeRegisteredDate 2021-06-14 00:00:00 for CaseMasterID 988
Warning: ArrestSurrenderDate 2022-08-15 00:00:00 is before one day after CrimeRegisteredDate 2022-08-16 00:00:00 for CaseMasterID 1002
Warning: ArrestSurrenderDate 2021-03-16 00:00:00 is before one day after CrimeRegisteredDate 2021-03-17 00:00:00 for CaseMasterID 1004
Warning: ArrestSurrenderDate 2026-03-07 00:00:00 is before one day after CrimeRegisteredDate 2026-03-08 00:00:00 for CaseMasterID 1010
Warning: ArrestSurrenderDate 2023-01-20 00:00:00 is before one day after CrimeRegisteredDate 2023-01-21 00:00:00 for CaseMasterID 1015
Warning: ArrestSurrenderDate 2023-03-05 00:00:00 is before one day after CrimeRegisteredDate 2023-03-06 00:00:00 for CaseMasterID 1022
Warning: ArrestSurrenderDate 2025-01-18 00:00:00 is before one day after CrimeRegisteredDate 2025-01-19 00:00:00 for CaseMasterID 1030

In [56]:
## Just to check if the ArrestSurrender dataframe's ArrestSurrenderDate is after one day of the IncidentToDate in CaseMaster dataframe
for index, row in ArrestSurrender.iterrows():
    case_id = row['CaseMasterID']
    arrest_date = row['ArrestSurrenderDate']
    incident_to_date = CaseMaster.loc[CaseMaster['CaseMasterID'] == case_id, 'IncidentToDate'].values[0]
    one_day_after_incident = incident_to_date + pd.Timedelta(days=1)

    if pd.notnull(arrest_date) and pd.notnull(incident_to_date) and arrest_date < one_day_after_incident:
        print(f"Warning: ArrestSurrenderDate {arrest_date} is before one day after IncidentToDate {one_day_after_incident} for CaseMasterID {case_id}")

Warning: ArrestSurrenderDate 2023-10-29 00:00:00 is before one day after IncidentToDate 2023-10-29 17:18:04 for CaseMasterID 3
Warning: ArrestSurrenderDate 2025-09-29 00:00:00 is before one day after IncidentToDate 2025-09-29 03:34:27 for CaseMasterID 15
Warning: ArrestSurrenderDate 2024-11-25 00:00:00 is before one day after IncidentToDate 2024-11-25 17:55:28 for CaseMasterID 20
Warning: ArrestSurrenderDate 2023-10-05 00:00:00 is before one day after IncidentToDate 2023-10-06 00:41:06 for CaseMasterID 33
Warning: ArrestSurrenderDate 2024-07-23 00:00:00 is before one day after IncidentToDate 2024-07-23 17:05:55 for CaseMasterID 46
Warning: ArrestSurrenderDate 2025-02-16 00:00:00 is before one day after IncidentToDate 2025-02-16 03:11:16 for CaseMasterID 76
Warning: ArrestSurrenderDate 2022-10-05 00:00:00 is before one day after IncidentToDate 2022-10-05 06:58:32 for CaseMasterID 79
Warning: ArrestSurrenderDate 2022-10-05 00:00:00 is before one day after IncidentToDate 2022-10-05 06:58:32 for CaseMasterID 79
Warning: ArrestSurrenderDate 2024-05-03 00:00:00 is before one day after IncidentToDate 2024-05-03 00:00:17 for CaseMasterID 80
Warning: ArrestSurrenderDate 2024-10-26 00:00:00 is before one day after IncidentToDate 2024-10-27 06:09:30 for CaseMasterID 83
Warning: ArrestSurrenderDate 2022-10-30 00:00:00 is before one day after IncidentToDate 2022-10-30 21:30:36 for CaseMasterID 95
Warning: ArrestSurrenderDate 2025-03-16 00:00:00 is before one day after IncidentToDate 2025-03-17 09:58:16 for CaseMasterID 98
Warning: ArrestSurrenderDate 2023-05-13 00:00:00 is before one day after IncidentToDate 2023-05-13 23:34:25 for CaseMasterID 113
Warning: ArrestSurrenderDate 2023-05-13 00:00:00 is before one day after IncidentToDate 2023-05-13 23:34:25 for CaseMasterID 113
Warning: ArrestSurrenderDate 2023-06-23 00:00:00 is before one day after IncidentToDate 2023-06-23 04:33:09 for CaseMasterID 125
Warning: ArrestSurrenderDate 2025-02-06 00:00:00 is before one day after IncidentToDate 2025-02-06 16:42:50 for CaseMasterID 130
Warning: ArrestSurrenderDate 2022-10-11 00:00:00 is before one day after IncidentToDate 2022-10-11 02:28:05 for CaseMasterID 138
Warning: ArrestSurrenderDate 2023-08-08 00:00:00 is before one day after IncidentToDate 2023-08-09 12:54:28 for CaseMasterID 145
Warning: ArrestSurrenderDate 2021-10-23 00:00:00 is before one day after IncidentToDate 2021-10-24 15:41:57 for CaseMasterID 150
Warning: ArrestSurrenderDate 2021-10-21 00:00:00 is before one day after IncidentToDate 2021-10-24 15:41:57 for CaseMasterID 150
Warning: ArrestSurrenderDate 2025-10-23 00:00:00 is before one day after IncidentToDate 2025-10-24 16:00:06 for CaseMasterID 152
Warning: ArrestSurrenderDate 2022-08-09 00:00:00 is before one day after IncidentToDate 2022-08-09 20:30:53 for CaseMasterID 175
Warning: ArrestSurrenderDate 2025-01-20 00:00:00 is before one day after IncidentToDate 2025-01-21 13:57:30 for CaseMasterID 188
Warning: ArrestSurrenderDate 2021-11-07 00:00:00 is before one day after IncidentToDate 2021-11-07 20:14:55 for CaseMasterID 190
Warning: ArrestSurrenderDate 2024-11-10 00:00:00 is before one day after IncidentToDate 2024-11-11 00:33:29 for CaseMasterID 193
Warning: ArrestSurrenderDate 2024-11-11 00:00:00 is before one day after IncidentToDate 2024-11-11 00:33:29 for CaseMasterID 193
Warning: ArrestSurrenderDate 2023-10-26 00:00:00 is before one day after IncidentToDate 2023-10-26 15:16:52 for CaseMasterID 195
Warning: ArrestSurrenderDate 2021-08-25 00:00:00 is before one day after IncidentToDate 2021-08-25 10:37:40 for CaseMasterID 197
Warning: ArrestSurrenderDate 2022-09-17 00:00:00 is before one day after IncidentToDate 2022-09-17 09:07:27 for CaseMasterID 230
Warning: ArrestSurrenderDate 2026-05-09 00:00:00 is before one day after IncidentToDate 2026-05-10 15:03:05 for CaseMasterID 238
Warning: ArrestSurrenderDate 2024-10-01 00:00:00 is before one day after IncidentToDate 2024-10-05 11:46:58 for CaseMasterID 251
Warning: ArrestSurrenderDate 2024-10-01 00:00:00 is before one day after IncidentToDate 2024-10-05 11:46:58 for CaseMasterID 251
Warning: ArrestSurrenderDate 2025-07-20 00:00:00 is before one day after IncidentToDate 2025-07-20 05:15:58 for CaseMasterID 259
Warning: ArrestSurrenderDate 2022-09-11 00:00:00 is before one day after IncidentToDate 2022-09-12 00:25:32 for CaseMasterID 260
Warning: ArrestSurrenderDate 2022-09-11 00:00:00 is before one day after IncidentToDate 2022-09-12 00:25:32 for CaseMasterID 260
Warning: ArrestSurrenderDate 2025-03-16 00:00:00 is before one day after IncidentToDate 2025-03-17 16:35:35 for CaseMasterID 271
Warning: ArrestSurrenderDate 2026-06-05 00:00:00 is before one day after IncidentToDate 2026-06-06 01:17:33 for CaseMasterID 274
Warning: ArrestSurrenderDate 2022-06-24 00:00:00 is before one day after IncidentToDate 2022-06-25 16:04:43 for CaseMasterID 292
Warning: ArrestSurrenderDate 2022-06-23 00:00:00 is before one day after IncidentToDate 2022-06-25 16:04:43 for CaseMasterID 292
Warning: ArrestSurrenderDate 2022-06-24 00:00:00 is before one day after IncidentToDate 2022-06-25 16:04:43 for CaseMasterID 292
Warning: ArrestSurrenderDate 2022-06-22 00:00:00 is before one day after IncidentToDate 2022-06-25 16:04:43 for CaseMasterID 292
Warning: ArrestSurrenderDate 2022-06-23 00:00:00 is before one day after IncidentToDate 2022-06-25 16:04:43 for CaseMasterID 292
Warning: ArrestSurrenderDate 2022-03-15 00:00:00 is before one day after IncidentToDate 2022-03-16 17:18:11 for CaseMasterID 293
Warning: ArrestSurrenderDate 2024-08-28 00:00:00 is before one day after IncidentToDate 2024-08-29 13:14:57 for CaseMasterID 312
Warning: ArrestSurrenderDate 2023-04-22 00:00:00 is before one day after IncidentToDate 2023-04-24 05:00:54 for CaseMasterID 314
Warning: ArrestSurrenderDate 2025-10-07 00:00:00 is before one day after IncidentToDate 2025-10-07 14:59:58 for CaseMasterID 323
Warning: ArrestSurrenderDate 2023-05-21 00:00:00 is before one day after IncidentToDate 2023-05-21 21:17:16 for CaseMasterID 325
Warning: ArrestSurrenderDate 2023-08-15 00:00:00 is before one day after IncidentToDate 2023-08-19 00:06:47 for CaseMasterID 326
Warning: ArrestSurrenderDate 2023-08-16 00:00:00 is before one day after IncidentToDate 2023-08-19 00:06:47 for CaseMasterID 326
Warning: ArrestSurrenderDate 2022-03-01 00:00:00 is before one day after IncidentToDate 2022-03-01 14:44:29 for CaseMasterID 338
Warning: ArrestSurrenderDate 2022-03-01 00:00:00 is before one day after IncidentToDate 2022-03-01 14:44:29 for CaseMasterID 338
Warning: ArrestSurrenderDate 2025-05-22 00:00:00 is before one day after IncidentToDate 2025-05-23 08:57:04 for CaseMasterID 341
Warning: ArrestSurrenderDate 2023-03-26 00:00:00 is before one day after IncidentToDate 2023-03-26 07:36:03 for CaseMasterID 354
Warning: ArrestSurrenderDate 2024-02-18 00:00:00 is before one day after IncidentToDate 2024-02-19 00:24:44 for CaseMasterID 355
Warning: ArrestSurrenderDate 2024-03-16 00:00:00 is before one day after IncidentToDate 2024-03-18 01:01:46 for CaseMasterID 364
Warning: ArrestSurrenderDate 2025-03-18 00:00:00 is before one day after IncidentToDate 2025-03-18 11:31:33 for CaseMasterID 375
Warning: ArrestSurrenderDate 2022-09-16 00:00:00 is before one day after IncidentToDate 2022-09-17 19:35:21 for CaseMasterID 376
Warning: ArrestSurrenderDate 2022-01-23 00:00:00 is before one day after IncidentToDate 2022-01-23 01:43:44 for CaseMasterID 388
Warning: ArrestSurrenderDate 2022-11-11 00:00:00 is before one day after IncidentToDate 2022-11-11 09:55:34 for CaseMasterID 393
Warning: ArrestSurrenderDate 2024-01-15 00:00:00 is before one day after IncidentToDate 2024-01-15 08:08:18 for CaseMasterID 396
Warning: ArrestSurrenderDate 2025-09-18 00:00:00 is before one day after IncidentToDate 2025-09-18 07:56:36 for CaseMasterID 397
Warning: ArrestSurrenderDate 2026-03-01 00:00:00 is before one day after IncidentToDate 2026-03-02 00:36:22 for CaseMasterID 401
Warning: ArrestSurrenderDate 2023-08-06 00:00:00 is before one day after IncidentToDate 2023-08-06 14:23:45 for CaseMasterID 407
Warning: ArrestSurrenderDate 2025-04-01 00:00:00 is before one day after IncidentToDate 2025-04-01 09:07:56 for CaseMasterID 419
Warning: ArrestSurrenderDate 2025-04-01 00:00:00 is before one day after IncidentToDate 2025-04-01 09:07:56 for CaseMasterID 419
Warning: ArrestSurrenderDate 2023-01-12 00:00:00 is before one day after IncidentToDate 2023-01-12 15:14:47 for CaseMasterID 421
Warning: ArrestSurrenderDate 2025-11-02 00:00:00 is before one day after IncidentToDate 2025-11-02 04:34:08 for CaseMasterID 425
Warning: ArrestSurrenderDate 2023-11-23 00:00:00 is before one day after IncidentToDate 2023-11-23 08:59:30 for CaseMasterID 436
Warning: ArrestSurrenderDate 2026-02-26 00:00:00 is before one day after IncidentToDate 2026-02-27 05:15:11 for CaseMasterID 441
Warning: ArrestSurrenderDate 2023-03-30 00:00:00 is before one day after IncidentToDate 2023-03-30 13:51:07 for CaseMasterID 442
Warning: ArrestSurrenderDate 2023-03-30 00:00:00 is before one day after IncidentToDate 2023-03-30 13:51:07 for CaseMasterID 442
Warning: ArrestSurrenderDate 2025-03-02 00:00:00 is before one day after IncidentToDate 2025-03-03 00:03:00 for CaseMasterID 446
Warning: ArrestSurrenderDate 2021-12-31 00:00:00 is before one day after IncidentToDate 2022-01-03 05:24:37 for CaseMasterID 450
Warning: ArrestSurrenderDate 2023-12-19 00:00:00 is before one day after IncidentToDate 2023-12-20 07:08:30 for CaseMasterID 458
Warning: ArrestSurrenderDate 2023-12-19 00:00:00 is before one day after IncidentToDate 2023-12-20 07:08:30 for CaseMasterID 458
Warning: ArrestSurrenderDate 2021-08-22 00:00:00 is before one day after IncidentToDate 2021-08-22 23:28:32 for CaseMasterID 463
Warning: ArrestSurrenderDate 2024-02-07 00:00:00 is before one day after IncidentToDate 2024-02-07 05:07:51 for CaseMasterID 471
Warning: ArrestSurrenderDate 2024-02-07 00:00:00 is before one day after IncidentToDate 2024-02-07 05:07:51 for CaseMasterID 471
Warning: ArrestSurrenderDate 2025-11-05 00:00:00 is before one day after IncidentToDate 2025-11-06 02:16:07 for CaseMasterID 476
Warning: ArrestSurrenderDate 2025-08-22 00:00:00 is before one day after IncidentToDate 2025-08-22 07:37:11 for CaseMasterID 480
Warning: ArrestSurrenderDate 2023-10-05 00:00:00 is before one day after IncidentToDate 2023-10-07 01:01:03 for CaseMasterID 500
Warning: ArrestSurrenderDate 2022-04-21 00:00:00 is before one day after IncidentToDate 2022-04-22 15:02:45 for CaseMasterID 503
Warning: ArrestSurrenderDate 2023-12-13 00:00:00 is before one day after IncidentToDate 2023-12-13 02:24:30 for CaseMasterID 506
Warning: ArrestSurrenderDate 2025-09-05 00:00:00 is before one day after IncidentToDate 2025-09-05 01:51:22 for CaseMasterID 510
Warning: ArrestSurrenderDate 2025-09-05 00:00:00 is before one day after IncidentToDate 2025-09-05 01:51:22 for CaseMasterID 510
Warning: ArrestSurrenderDate 2023-01-05 00:00:00 is before one day after IncidentToDate 2023-01-05 00:41:37 for CaseMasterID 511
Warning: ArrestSurrenderDate 2022-11-06 00:00:00 is before one day after IncidentToDate 2022-11-06 08:46:04 for CaseMasterID 523
Warning: ArrestSurrenderDate 2022-02-12 00:00:00 is before one day after IncidentToDate 2022-02-12 12:58:14 for CaseMasterID 527
Warning: ArrestSurrenderDate 2024-08-07 00:00:00 is before one day after IncidentToDate 2024-08-08 01:35:27 for CaseMasterID 530
Warning: ArrestSurrenderDate 2023-11-16 00:00:00 is before one day after IncidentToDate 2023-11-16 22:44:48 for CaseMasterID 533
Warning: ArrestSurrenderDate 2023-05-30 00:00:00 is before one day after IncidentToDate 2023-05-30 14:19:59 for CaseMasterID 536
Warning: ArrestSurrenderDate 2025-03-10 00:00:00 is before one day after IncidentToDate 2025-03-10 10:37:14 for CaseMasterID 537
Warning: ArrestSurrenderDate 2025-03-18 00:00:00 is before one day after IncidentToDate 2025-03-18 13:53:12 for CaseMasterID 546
Warning: ArrestSurrenderDate 2023-06-09 00:00:00 is before one day after IncidentToDate 2023-06-10 12:52:29 for CaseMasterID 547
Warning: ArrestSurrenderDate 2025-04-20 00:00:00 is before one day after IncidentToDate 2025-04-20 07:59:41 for CaseMasterID 549
Warning: ArrestSurrenderDate 2022-03-07 00:00:00 is before one day after IncidentToDate 2022-03-07 14:40:42 for CaseMasterID 551
Warning: ArrestSurrenderDate 2022-05-16 00:00:00 is before one day after IncidentToDate 2022-05-16 05:30:07 for CaseMasterID 559
Warning: ArrestSurrenderDate 2023-06-10 00:00:00 is before one day after IncidentToDate 2023-06-10 14:21:57 for CaseMasterID 583
Warning: ArrestSurrenderDate 2023-06-10 00:00:00 is before one day after IncidentToDate 2023-06-10 14:21:57 for CaseMasterID 583
Warning: ArrestSurrenderDate 2023-06-07 00:00:00 is before one day after IncidentToDate 2023-06-10 14:21:57 for CaseMasterID 583
Warning: ArrestSurrenderDate 2022-04-09 00:00:00 is before one day after IncidentToDate 2022-04-10 14:12:42 for CaseMasterID 584
Warning: ArrestSurrenderDate 2022-04-09 00:00:00 is before one day after IncidentToDate 2022-04-10 14:12:42 for CaseMasterID 584
Warning: ArrestSurrenderDate 2025-07-21 00:00:00 is before one day after IncidentToDate 2025-07-22 22:18:10 for CaseMasterID 590
Warning: ArrestSurrenderDate 2024-06-22 00:00:00 is before one day after IncidentToDate 2024-06-22 08:02:27 for CaseMasterID 595
Warning: ArrestSurrenderDate 2026-06-29 00:00:00 is before one day after IncidentToDate 2026-06-30 08:25:45 for CaseMasterID 596
Warning: ArrestSurrenderDate 2026-06-30 00:00:00 is before one day after IncidentToDate 2026-06-30 08:25:45 for CaseMasterID 596
Warning: ArrestSurrenderDate 2026-06-26 00:00:00 is before one day after IncidentToDate 2026-06-30 08:25:45 for CaseMasterID 596
Warning: ArrestSurrenderDate 2024-01-10 00:00:00 is before one day after IncidentToDate 2024-01-10 18:53:17 for CaseMasterID 605
Warning: ArrestSurrenderDate 2022-10-31 00:00:00 is before one day after IncidentToDate 2022-10-31 13:55:25 for CaseMasterID 606
Warning: ArrestSurrenderDate 2024-02-11 00:00:00 is before one day after IncidentToDate 2024-02-13 21:31:34 for CaseMasterID 614
Warning: ArrestSurrenderDate 2024-02-13 00:00:00 is before one day after IncidentToDate 2024-02-13 21:31:34 for CaseMasterID 614
Warning: ArrestSurrenderDate 2025-04-04 00:00:00 is before one day after IncidentToDate 2025-04-04 07:54:59 for CaseMasterID 634
Warning: ArrestSurrenderDate 2025-06-16 00:00:00 is before one day after IncidentToDate 2025-06-16 21:09:23 for CaseMasterID 636
Warning: ArrestSurrenderDate 2024-06-03 00:00:00 is before one day after IncidentToDate 2024-06-05 08:00:06 for CaseMasterID 638
Warning: ArrestSurrenderDate 2026-01-19 00:00:00 is before one day after IncidentToDate 2026-01-19 07:00:04 for CaseMasterID 643
Warning: ArrestSurrenderDate 2023-09-06 00:00:00 is before one day after IncidentToDate 2023-09-06 01:08:57 for CaseMasterID 644
Warning: ArrestSurrenderDate 2024-05-17 00:00:00 is before one day after IncidentToDate 2024-05-17 10:57:14 for CaseMasterID 645
Warning: ArrestSurrenderDate 2024-06-03 00:00:00 is before one day after IncidentToDate 2024-06-03 10:12:51 for CaseMasterID 655
Warning: ArrestSurrenderDate 2024-09-29 00:00:00 is before one day after IncidentToDate 2024-09-29 05:56:51 for CaseMasterID 662
Warning: ArrestSurrenderDate 2022-02-02 00:00:00 is before one day after IncidentToDate 2022-02-02 01:40:17 for CaseMasterID 666
Warning: ArrestSurrenderDate 2026-07-16 00:00:00 is before one day after IncidentToDate 2026-07-16 00:33:51 for CaseMasterID 692
Warning: ArrestSurrenderDate 2021-04-13 00:00:00 is before one day after IncidentToDate 2021-04-13 00:47:31 for CaseMasterID 702
Warning: ArrestSurrenderDate 2024-12-21 00:00:00 is before one day after IncidentToDate 2024-12-21 00:05:29 for CaseMasterID 707
Warning: ArrestSurrenderDate 2025-05-06 00:00:00 is before one day after IncidentToDate 2025-05-06 00:05:29 for CaseMasterID 711
Warning: ArrestSurrenderDate 2025-07-15 00:00:00 is before one day after IncidentToDate 2025-07-15 14:26:05 for CaseMasterID 712
Warning: ArrestSurrenderDate 2025-07-15 00:00:00 is before one day after IncidentToDate 2025-07-15 14:26:05 for CaseMasterID 712
Warning: ArrestSurrenderDate 2022-10-05 00:00:00 is before one day after IncidentToDate 2022-10-07 20:03:02 for CaseMasterID 714
Warning: ArrestSurrenderDate 2025-01-30 00:00:00 is before one day after IncidentToDate 2025-01-31 02:12:16 for CaseMasterID 716
Warning: ArrestSurrenderDate 2025-02-03 00:00:00 is before one day after IncidentToDate 2025-02-04 16:39:28 for CaseMasterID 719
Warning: ArrestSurrenderDate 2025-02-01 00:00:00 is before one day after IncidentToDate 2025-02-04 16:39:28 for CaseMasterID 719
Warning: ArrestSurrenderDate 2025-02-27 00:00:00 is before one day after IncidentToDate 2025-02-28 03:19:35 for CaseMasterID 738
Warning: ArrestSurrenderDate 2021-07-23 00:00:00 is before one day after IncidentToDate 2021-07-23 13:29:15 for CaseMasterID 739
Warning: ArrestSurrenderDate 2021-06-15 00:00:00 is before one day after IncidentToDate 2021-06-15 16:23:59 for CaseMasterID 768
Warning: ArrestSurrenderDate 2022-05-20 00:00:00 is before one day after IncidentToDate 2022-05-20 10:21:23 for CaseMasterID 770
Warning: ArrestSurrenderDate 2021-06-14 00:00:00 is before one day after IncidentToDate 2021-06-15 06:27:04 for CaseMasterID 771
Warning: ArrestSurrenderDate 2025-09-26 00:00:00 is before one day after IncidentToDate 2025-09-27 13:13:40 for CaseMasterID 772
Warning: ArrestSurrenderDate 2024-09-16 00:00:00 is before one day after IncidentToDate 2024-09-17 10:57:48 for CaseMasterID 777
Warning: ArrestSurrenderDate 2025-03-11 00:00:00 is before one day after IncidentToDate 2025-03-13 02:52:54 for CaseMasterID 780
Warning: ArrestSurrenderDate 2026-03-26 00:00:00 is before one day after IncidentToDate 2026-03-27 16:09:07 for CaseMasterID 797
Warning: ArrestSurrenderDate 2026-03-27 00:00:00 is before one day after IncidentToDate 2026-03-27 16:09:07 for CaseMasterID 797
Warning: ArrestSurrenderDate 2021-06-20 00:00:00 is before one day after IncidentToDate 2021-06-20 16:35:14 for CaseMasterID 800
Warning: ArrestSurrenderDate 2021-02-10 00:00:00 is before one day after IncidentToDate 2021-02-10 18:06:14 for CaseMasterID 807
Warning: ArrestSurrenderDate 2024-05-31 00:00:00 is before one day after IncidentToDate 2024-06-01 13:20:24 for CaseMasterID 808
Warning: ArrestSurrenderDate 2023-12-19 00:00:00 is before one day after IncidentToDate 2023-12-20 10:57:52 for CaseMasterID 809
Warning: ArrestSurrenderDate 2023-12-19 00:00:00 is before one day after IncidentToDate 2023-12-20 10:57:52 for CaseMasterID 809
Warning: ArrestSurrenderDate 2025-02-18 00:00:00 is before one day after IncidentToDate 2025-02-19 05:32:33 for CaseMasterID 811
Warning: ArrestSurrenderDate 2023-10-24 00:00:00 is before one day after IncidentToDate 2023-10-24 20:15:37 for CaseMasterID 815
Warning: ArrestSurrenderDate 2024-03-20 00:00:00 is before one day after IncidentToDate 2024-03-20 06:46:13 for CaseMasterID 818
Warning: ArrestSurrenderDate 2025-08-07 00:00:00 is before one day after IncidentToDate 2025-08-07 07:40:48 for CaseMasterID 824
Warning: ArrestSurrenderDate 2025-08-19 00:00:00 is before one day after IncidentToDate 2025-08-20 12:25:48 for CaseMasterID 835
Warning: ArrestSurrenderDate 2025-04-24 00:00:00 is before one day after IncidentToDate 2025-04-24 14:59:52 for CaseMasterID 838
Warning: ArrestSurrenderDate 2026-02-18 00:00:00 is before one day after IncidentToDate 2026-02-18 06:10:33 for CaseMasterID 845
Warning: ArrestSurrenderDate 2025-09-05 00:00:00 is before one day after IncidentToDate 2025-09-05 05:39:45 for CaseMasterID 846
Warning: ArrestSurrenderDate 2023-02-24 00:00:00 is before one day after IncidentToDate 2023-02-24 09:23:32 for CaseMasterID 849
Warning: ArrestSurrenderDate 2024-05-11 00:00:00 is before one day after IncidentToDate 2024-05-12 11:21:04 for CaseMasterID 868

In [ ]:
### How to clean this up??